language: erlang

# Choose which platforms you want your builds run against (done in parallel)
env:
   matrix:
   - ST=Squeak-4.5 SCAMPER_SCREENSHOT=true
   - ST=Squeak-Trunk
   global:
     secure: PkDb5LAmq3k4O4wXLPhCq5GdlEBjaMJ8B7sAK36Rb9rg223OBYs8I+mTp9TB1O5DVu+4Q5o5EUmG5+lkiPINzXcDyPMpnw9zx7kZdA4LaiBpeiVtKH/2+t5hgD4KDWkXYdoINuIahOZsZcKzlibQ1aDcXN61A1qzQAo9BT4CbbU=

# For SqueakSSL
before_install:
   - sudo apt-get -qq install libssl0.9.8:i386

# Boilerplate ... should be no reason to edit the install section
install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O builderCI.zip https://github.com/SWTI2014/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd SWTI2014-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

# use a different script if you want to customize how travis tests are run
# use verbose flag to dump transcript unconditionally
script: $BUILDER_CI_HOME/testTravisCI.sh # -verbose 
after_success:
   - chmod -R 777 $PROJECT_HOME/build-support/*.sh
   - $PROJECT_HOME/build-support/screenshots.sh
